### PR TITLE
Add payment feature and record

### PR DESCRIPTION
**Pull request by tk-wong**
This pull request introduces a new `ExternalAPI` interface and its implementation for simulating the payment process using the Octopus card API. It includes corresponding factory classes, payment classes, and test cases. Additionally, it updates the `PaymentRecord` class and modifies the `Movie` class in test files to include a new parameter.

### New External API Implementation:

* [`src/ExternalAPI/ExternalAPI.java`](diffhunk://#diff-a3c14c023a125172662b6e7f297efdd99582f9a32262e7a861ba75d5814b16efR1-R9): Added `ExternalAPI` interface to simulate the payment process.
* [`src/ExternalAPI/ExternalAPIFactory.java`](diffhunk://#diff-81da5bc2e7143bcfd9ade64bbec968335abff54f352a32ed686c9aceff13b520R1-R21): Added `ExternalAPIFactory` interface for creating `ExternalAPI` objects.
* [`src/ExternalAPI/OctopusAPI.java`](diffhunk://#diff-ecf437e8f8d87497f9ada002c5a40a32f25ffe73a160ca5349d91de97e3eb89aR1-R38): Added `OctopusAPI` class implementing `ExternalAPI` to simulate Octopus card payments.
* [`src/ExternalAPI/OctopusAPIFactory.java`](diffhunk://#diff-9f1598a8b38dda314a41b1b6fd57d0e29ce1d726855f0f824bb4428b3f1adf1bR1-R28): Added `OctopusAPIFactory` class implementing `ExternalAPIFactory` to create `OctopusAPI` objects.

### Payment System Enhancements:

* [`src/Payment/OctopusPayment.java`](diffhunk://#diff-10e6f21507b12beeccd13a075abcc3af96f89fcf07ebf0593a39e14b6980878bR1-R38): Added `OctopusPayment` class to handle payments using the Octopus card.
* [`src/Payment/OctopusPaymentFactory.java`](diffhunk://#diff-65043f03ed130967028b6403d0b6172f91c5c38302f82a845c10b49958113ca7R1-R13): Added `OctopusPaymentFactory` class to create `OctopusPayment` objects.
* [`src/Payment/Payment.java`](diffhunk://#diff-34b78277a0f7c3fe0b23f48b02d1cbacdc96325198ac32aae977ad6f83f35954R3-R21): Updated `Payment` interface with documentation and additional methods.
* [`src/Payment/PaymentFactory.java`](diffhunk://#diff-0c2ca4675f15190a161b4e03c6b255fd2acc7e1d6a17e07c6ebce301989b0f65R1-R13): Added `PaymentFactory` interface for creating `Payment` objects.
* [`src/Payment/PaymentType.java`](diffhunk://#diff-83f408257b310e181dffe03ddd85b2f124ab26896d9ddcebb3293c7b13fe1200R1-R9): Added `PaymentType` enum to represent different payment types.

### Record Management:

* [`src/Record/PaymentRecord.java`](diffhunk://#diff-8a86085ab82069ed6fc217cbccd5a409f940763b7f12e22703c02a78c28e486eR1-R35): Added `PaymentRecord` class to store payment records, including customer, products, movies, and payment details.

### Testing:

* [`src/Test/TestExternalAPI/OctopusAPITest.java`](diffhunk://#diff-df97316c49cea0ec51b6f55d4f4e1acdb68e18c2f2fec1e557e2494d1f9761f2R1-R71): Added tests for `OctopusAPI` and `OctopusAPIFactory` classes.
* [`src/Test/TestPayment/OctopusPaymentTest.java`](diffhunk://#diff-4fc3a3dcc4f55eaaa64b7bff6d3bb6c7b04b50e03db02aae35f9722174d2e2a0R1-R80): Added tests for `OctopusPayment` and `OctopusPaymentFactory` classes.
* [`src/Test/TestRecord/PaymentRecordTest.java`](diffhunk://#diff-71bddfea3dd5083517a4dc6fa9d5ed7d01c4d19b08f9b5c7390307a5ee3ac01cR1-R88): Added tests for `PaymentRecord` class.

### Minor Updates:

* [`src/Test/TestShoppingCart/ShoppingCartTest.java`](diffhunk://#diff-d17770648ba055c94bf10d489ddf2a666a36dc6b4170ea77d18fef15a84b1d5bL33-R34): Updated `Movie` class instantiation to include a new parameter in multiple test methods. [[1]](diffhunk://#diff-d17770648ba055c94bf10d489ddf2a666a36dc6b4170ea77d18fef15a84b1d5bL33-R34) [[2]](diffhunk://#diff-d17770648ba055c94bf10d489ddf2a666a36dc6b4170ea77d18fef15a84b1d5bL77-R77) [[3]](diffhunk://#diff-d17770648ba055c94bf10d489ddf2a666a36dc6b4170ea77d18fef15a84b1d5bL107-R107) [[4]](diffhunk://#diff-d17770648ba055c94bf10d489ddf2a666a36dc6b4170ea77d18fef15a84b1d5bL175-R175)

### Note
* The Octopus Card payment (`OctopusPayment` and `OctopusPaymentFactory` ) and External API (`OctopusAPI` and  `OctopusAPIFactory` ) demonstrate the payment process. If there is no problem, other payments and their External API will be implemented like them. All payment methods that will be implemented are shown in the `PaymentType` Enum.

### CODE REVIEW

**Review by KHC-FTW — COMMENTED** [review]
I think payment price could be better with 'double', but not 'int'

For payment records, I think there should be more attributes like movie session chosen, seats booked for that particular session, instead of putting the movie object directly. (Let me handle the revision of these parts later)

**Comment by tk-wong** [comment]
ok
Then I will also change the price of snacks and drinks to double

**Comment by tk-wong** [comment]
How about a shopping cart? Should it also shore the movie session and seats?

**Comment by KHC-FTW** [comment]
I think can, in customer lclass, i think i have a cache for selected movie session and seats, they are temporary backup and if payment success, they will be stored permanently in some other classes, maybe payment record

**Comment by KHC-FTW** [comment]
actually, the database class should be the final location to save all important data, so apart from a static List<PaymentRecord> that stores all payment records, you may consider the database class as the second location to store all these records. This will be implemented when most of the codes are finalized and I know the logic of what each class is doing

**Comment by tk-wong** [comment]
I think I will modify the record class to store the data in the database when the database class for the record is finished.
Also, I just changed the price to double, but I found this pull request is closed and merged. I will create another pull request for this, the modified record class and shopping cart class  (which I haven't finished).

**Pull request merged**
